### ISSUE TITLE
Options endpoint does not return all options

### ISSUE THREAD

**Issue by RichardHeelin** [bigcommerce/api#21] opened 2016-08-01 10:57 UTC
The new options endpoint (`/stores/{storeHash}/v3/catalog/products/{productId}/options`) does not always return any options associated with the passed product id. This seems to be an issue with either the sample products created automatically with the creation of a test store, or with products created before the new api.

Steps to reproduce:
- Get product information for a sample product which has options associated with their variants
  `/stores/{storeHash}/v3/catalog/products/93?include=images%2Cvariants`

```
{
    "data":{
        "id":93,
        "name":"[Sample] 1 L Le Parfait Jar",
        "type":"physical",
        "sku":"SLLPJ",
        ...
        "variants":[
            {
                "id":46,
                "product_id":93,
                "sku":"SLLPJ-6088C959",
                ...
                "option_values":[
                    { "id":7, "option_id":111 },
                    { "id":95, "option_id":112 }
                ]
            },
            {
                "id":47,
                "product_id":93,
                "sku":"SLLPJ-20D88EFC",
                ...
                "option_values":[
                    { "id":8, "option_id":111 },
                    { "id":95, "option_id":112
                    }
                ]
            },
            ...
        ],
        ...
    },
    "meta":{

    }
}
```
- Fetch options for product
  `/stores/{storeHash}/v3/catalog/products/93/options`

```
{"data":[],"meta":{}}
```

Expected behaviour is to get the options returned with their values. If I create a new product and setup it's options through the ui, the above works as expected.

**Comment by ICarpenter** [comment] 2016-08-09 17:51
@RichardHeelin Thank you for the feedback. I am an engineer on the BigCommerce API. There are some issues with the sample data that will be fixed in the short term. 

The cause of this confusion is that we now differentiate between options and modifiers. Options are used for creating variants (SKUs in v2) and modifiers are not. Many existing options, whether they are part of a SKU or not, are marked as modifiers. Modifiers are therefore the default state of a v2 option. 

Any variants created using v3 must be combinations of v3 options, modifiers are not accepted. In the v2 API, logic has been added to migrate any existing options used in creating a SKU to return properly in the v3 API's options endpoint.

We are working on an eventual migration that will allow existing stores to work more fluidly between v3 and v2.

**Comment by bc-AlyssNoland** [comment] 2017-04-05 00:15
Closing, please reopen if necessary.

**Closed by bc-AlyssNoland** 2017-04-05 00:15 UTC
