### ISSUE TITLE
incorrect response while adding id filter on GET products info (Absolute blocker)

### ISSUE THREAD

**Issue by vbharath2809** [bigcommerce/api#117] opened 2018-12-21 11:30 UTC
### Expected behavior

Id filter on [GET All products](https://developer.bigcommerce.com/api-reference/catalog/catalog-api/products/getproducts) info used to work perfectly i.e if we add 3 ids on the filter, it used to give only those 3 results if all of the ids are valid

### Actual behavior

Currently, it's considering the first one and getting only one product as the response.

### Steps to reproduce the behavior

URL: https://api.bigcommerce.com/stores/{$$.env.store_hash}/v3/catalog/products?include=custom_fields&id=id1,id2
Method - GET
expected result: it should return both item's data but it's returning only the id1 data.

Severity: Because of this issue, our entire integration got stuck and multiple customers are getting impacted. Please advise.

**Comment by bookernath** [comment] 2018-12-21 13:18
Use [?id:in=1,2,3](https://developer.bigcommerce.com/api-docs/getting-started/basics/filtering)

This is the means of providing an array of IDs.

the ?id= filter was intended for providing a single ID. I'll raise this regression with our team, as others might be affected, and we'll see what we can do - but for your purposes (and for an immediate fix) I'd recommend moving to ?id:in.

**Comment by bookernath** [comment] 2018-12-21 16:13
This should be "fixed" now, but please keep in mind this is not supported behavior. Use ?id:in= instead to be on the supported path.

In the future, you can get a faster response by getting in touch with our support team. Thanks!

**Closed by bookernath** 2018-12-21 16:13 UTC
